substitutions:
  _SHORT_SHA: latest

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aria:${_SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aria:${_SHORT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - aria
      - --image=gcr.io/$PROJECT_ID/aria:${_SHORT_SHA}
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=4Gi
      - --cpu=2
      - --timeout=600
      - --concurrency=80
      - --min-instances=0
      - --max-instances=10
      - --env-vars-file=env.yaml
images:
  - 'gcr.io/$PROJECT_ID/aria:${_SHORT_SHA}'